name = "declarativebanbot"
main = "bin/src/main.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd .. && make build"
watch_dir = ["../src"]

[[d1_databases]]
binding = "DB"
database_name = "ANROID_DECLARATIVE_BAN_BOT_DB"
database_id = "4b30e2e2-430e-4a9c-ac7b-acba5fd73a45"

[observability]
enabled = true
head_sampling_rate = 1
