name = "declarativebanbot"
main = "bin/src/main.js"
compatibility_date = "2023-10-30"
node_compat = true

[build]
command = "cd .. && make build"
watch_dir = ["../src"]

[[d1_databases]]
binding = "DB"
database_name = "ANROID_DECLARATIVE_BAN_BOT_DB"
database_id = "4b30e2e2-430e-4a9c-ac7b-acba5fd73a45"